### ISSUE TITLE
[register] page register perlu dipercantik

### ISSUE THREAD

**Issue by elberthomax** [stevelukis/SmartRestaurant#10]
![image](https://user-images.githubusercontent.com/38391861/48978955-dcace080-f0ee-11e8-9b18-eef7d4835216.png)

**Comment by andiwijayaid** [comment]
Sudah di percantik gan, tapi perlu samakan ulang idnya dengan JS. Monggo mas, dikerjakan.
tolong di cek ulang @elberthomax

**Comment by stevelukis** [comment]
bukan perlu dipercantik, memang belum selesai dikerja -___- @elberthomax
