### ISSUE TITLE
[customer] background modal order list terlalu gelap

### ISSUE THREAD

**Issue by elberthomax** [stevelukis/SmartRestaurant#18]
![image](https://user-images.githubusercontent.com/38391861/49373012-7ef44600-f737-11e8-8522-a654af079412.png)

**Comment by stevelukis** [comment]
sudah mi tugas basdat mu? @elberthomax

**Comment by elberthomax** [comment]
blum .-.

**Comment by andiwijayaid** [comment]
Done @elberthomax
