### ISSUE TITLE
add/update category internal server error

### ISSUE THREAD

**Issue by elberthomax** [stevelukis/SmartRestaurant#5]
![image](https://user-images.githubusercontent.com/38391861/48748910-82a5b880-ecb3-11e8-9bec-14449973caaa.png)

**Comment by elberthomax** [comment]
![image](https://user-images.githubusercontent.com/38391861/48749044-0b245900-ecb4-11e8-86a1-72c6a2e11673.png)

**Comment by stevelukis** [comment]
Masalah CORS di kau belum selesai, maka data tidak bisa terkirim ke server, sehingga data yang di pass null. Perbaiki dulu CORS di kau.

**Comment by stevelukis** [comment]
Check this out @elberthomax  https://stackoverflow.com/questions/35588699/response-to-preflight-request-doesnt-pass-access-control-check
