### ISSUE TITLE
get orders mengembalikan data tanpa memperdulikan table_number

### ISSUE THREAD

**Issue by elberthomax** [stevelukis/SmartRestaurant#6]
![image](https://user-images.githubusercontent.com/38391861/48749500-314af880-ecb6-11e8-8b17-1c7708d8d263.png)

**Comment by elberthomax** [comment]
table_number = 1
![image](https://user-images.githubusercontent.com/38391861/48816797-9407c700-ed7e-11e8-81da-42eee64f7933.png)
table_number = 2
![image](https://user-images.githubusercontent.com/38391861/48816827-b4d01c80-ed7e-11e8-8fe2-ef0fcf110179.png)
table_number = ""
![image](https://user-images.githubusercontent.com/38391861/48816856-d03b2780-ed7e-11e8-9e6d-bbcf29ebc9f8.png)

**Comment by stevelukis** [comment]
Fixed. @elberthomax
